/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tingleff.yassg.search.types;


public enum TSortFieldType implements org.apache.thrift.TEnum {
  IndexOrder(1),
  Double(2),
  Float(3),
  Integer(4),
  Long(5),
  Relevance(6),
  String(7);

  private final int value;

  private TSortFieldType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TSortFieldType findByValue(int value) { 
    switch (value) {
      case 1:
        return IndexOrder;
      case 2:
        return Double;
      case 3:
        return Float;
      case 4:
        return Integer;
      case 5:
        return Long;
      case 6:
        return Relevance;
      case 7:
        return String;
      default:
        return null;
    }
  }
}
